name: Claw
version: '${project.version}'
main: com.summit.claw.claw.Claw
api-version: '1.20'
authors: [ StakeTheSteak ]
description: C.L.A.W. (Collect, Locate, Annihilate, Win)
website: https://summitmc.xyz/
configuration-file: api_key.yml
commands:
  claw:
    description: Root command for C.L.A.W.
    aliases:
      - cl
    usage: /<command> [open|generate]
permissions:
  claw.open:
    description: Allows players to open the C.L.A.W. GUI.
    default: true
  claw.generate:
    description: Allows players to generate challenges.
    default: true