name: Claw
version: '1.0-BETA'
main: com.summit.claw.claw.Claw
api-version: '1.20'
authors: [ StakeTheSteak ]
description: C.L.A.W. (Collect, Locate, Annihilate, Win)
website: https://summitmc.xyz/
commands:
  claw-generate:
    description: Generates a challenge for the current in-game day
    usage: /claw-generate
    permission: claw.generate
    permission-message: &noperms "§cError: §fNo permission!"
  claw-open:
    description: Opens the menu GUI for C.L.A.W.
    usage: /claw-open
    permission: claw.open
    permission-message: &noperms "§cError: §fNo permission!"
permissions:
  claw.open:
    description: Allows players to open the C.L.A.W. GUI.
    default: true
  claw.generate:
    description: Allows players to generate challenges.
    default: true